language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: linux
      compiler: emcc
      dist: bionic
    - os: windows
      compiler: msvc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgl1-mesa-dev
    - x11proto-core-dev
    - libx11-dev
    - libsdl2-dev

script:
  - if [ "$TRAVIS_COMPILER" == "emcc" ]; then git clone https://github.com/emscripten-core/emsdk.git; fi
  - if [ "$TRAVIS_COMPILER" == "emcc" ]; then ./emsdk/emsdk install latest; fi
  - if [ "$TRAVIS_COMPILER" == "emcc" ]; then ./emsdk/emsdk activate latest; fi
  - if [ "$TRAVIS_COMPILER" == "emcc" ]; then source ./emsdk/emsdk_env.sh; fi
  - cmake -E make_directory build
  - cd build
  - if [ "$TRAVIS_COMPILER" == "emcc" ]; then python --version; fi
  - if [ "$TRAVIS_COMPILER" == "emcc" ]; then python3 --version; fi
  - if [ "$TRAVIS_COMPILER" == "emcc" ]; then emcmake cmake ..; else cmake .. -DCHERRYSODA_USE_SSE2=1; fi
  - cmake --build . --config Release

branches:
  only:
    - master

notifications:
  email: false
