language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: windows
      before_install:
        - python Tools/setup_sdl2_for_windows.py

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - libgl1-mesa-dev
    - x11proto-core-dev
    - libx11-dev
    - libsdl2-dev

script:
  - cmake -E make_directory build
  - cd build
  - cmake .. -DCHERRYSODA_USE_SSE2=1
  - cmake --build . --config Release

branches:
  only:
    - master

notifications:
  email: false
