language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: windows
      language: sh
      before_install:
        - git clone https://github.com/pyenv-win/pyenv-win.git $HOME/.pyenv
        - export PATH="$HOME/.pyenv/pyenv-win/bin:$HOME/.pyenv/pyenv-win/shims:$PATH"
        - pyenv install -q 3.7.1
        - pyenv rehash
        - pyenv local 3.7.1
        - python --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - libgl1-mesa-dev
    - x11proto-core-dev
    - libx11-dev
    - libsdl2-dev

script:
  - cmake -E make_directory build
  - cd build
  - cmake .. -DCHERRYSODA_USE_SSE2=1
  - cmake --build . --config Release

branches:
  only:
    - master

notifications:
  email: false
