name: Emscripten

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure Dependencies
      run: |
        sudo apt-get install build-essential libgl1-mesa-dev x11proto-core-dev libx11-dev libsdl2-dev

    - name: Configure emsdk
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        git clone https://github.com/emscripten-core/emsdk.git 
        ./emsdk/emsdk install latest
        ./emsdk/emsdk activate latest

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        source ../emsdk/emsdk_env.sh
        emcmake cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

