name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release, Profile]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libgl1-mesa-dev x11proto-core-dev libx11-dev libsdl2-dev

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{ matrix.build_type }} --parallel 10

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build/Tests
      run: TRACY_NO_INVARIANT_CHECK=1 ./AllTests
