name: Windows

on: [push, pull_request]

jobs:
  msvc-latest:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        architecture: [Win32, x64]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -A ${{ matrix.architecture }}

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{ matrix.build_type }} --parallel 10

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build/Tests
      run: ./${{ matrix.build_type }}/AllTests.exe
